# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: J. Frederico Carvalho
email: jfpbdc@kth.se
description: >
    Personal website of J. Frederico Carvalho</br>
    PhD student in CVAP</br>
    Royal Institute of Technology, KTH, Sweden</br>
baseurl: "." # the subpath of your site, e.g. /blog
url: "http://csc.kth.se/~jfpbdc" # the base hostname & protocol for your site
twitter_username: joaoCarvas
github_username:  crvs
adress: >
    João Carvalho,  <br>
    Teknikringen 14  <br>
    KTH Royal Institute of Technology  <br>
    114-28 Stockholm, Sweden

post_depth: "../../../../.."
disclaimer: "http://www.kth.se/gemensamt/disclaimer"
jekyll: "https://github.com/jekyll"

# Build settings
markdown: kramdown
