# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: J. Frederico Carvalho
email: jfpbdc@kth.se
description: >
    Personal page of J. Frederico Carvalho</br>
    PhD student at RPL</br>
    Royal Institute of Technology, KTH, Sweden</br>
url: "https://crvs.github.io" # the base hostname & protocol for your site
baseurl: "" # "." the subpath of your site, e.g. /blog


root: "https://crvs.github.io"

mastodon:
 - username: crvs
   instance: mastodon.social

twitter_username: joaoCarvas
github_username:  crvs
rss_username: crvs
adress: >
    João Carvalho,  <br>
    Teknikringen 14  <br>
    KTH Royal Institute of Technology  <br>
    114-28 Stockholm, Sweden

disclaimer: "http://www.kth.se/gemensamt/disclaimer"
jekyll: "https://github.com/jekyll"

collections:
    publications:
        output: true

#   projects:
#       output: false
#   blog:
#       output: false

# Build settings
markdown: kramdown

comments: true
disqus: "jfpbdc-csc-kth"

